// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/shippyproject/shippyproject.proto

package go_micro_srv_shippyproject

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Shippyproject service

type ShippyprojectService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Shippyproject_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Shippyproject_PingPongService, error)
}

type shippyprojectService struct {
	c    client.Client
	name string
}

func NewShippyprojectService(name string, c client.Client) ShippyprojectService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.shippyproject"
	}
	return &shippyprojectService{
		c:    c,
		name: name,
	}
}

func (c *shippyprojectService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Shippyproject.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippyprojectService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Shippyproject_StreamService, error) {
	req := c.c.NewRequest(c.name, "Shippyproject.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &shippyprojectServiceStream{stream}, nil
}

type Shippyproject_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type shippyprojectServiceStream struct {
	stream client.Stream
}

func (x *shippyprojectServiceStream) Close() error {
	return x.stream.Close()
}

func (x *shippyprojectServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippyprojectServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippyprojectServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shippyprojectService) PingPong(ctx context.Context, opts ...client.CallOption) (Shippyproject_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Shippyproject.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &shippyprojectServicePingPong{stream}, nil
}

type Shippyproject_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type shippyprojectServicePingPong struct {
	stream client.Stream
}

func (x *shippyprojectServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *shippyprojectServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippyprojectServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippyprojectServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *shippyprojectServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Shippyproject service

type ShippyprojectHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Shippyproject_StreamStream) error
	PingPong(context.Context, Shippyproject_PingPongStream) error
}

func RegisterShippyprojectHandler(s server.Server, hdlr ShippyprojectHandler, opts ...server.HandlerOption) error {
	type shippyproject interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Shippyproject struct {
		shippyproject
	}
	h := &shippyprojectHandler{hdlr}
	return s.Handle(s.NewHandler(&Shippyproject{h}, opts...))
}

type shippyprojectHandler struct {
	ShippyprojectHandler
}

func (h *shippyprojectHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ShippyprojectHandler.Call(ctx, in, out)
}

func (h *shippyprojectHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ShippyprojectHandler.Stream(ctx, m, &shippyprojectStreamStream{stream})
}

type Shippyproject_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type shippyprojectStreamStream struct {
	stream server.Stream
}

func (x *shippyprojectStreamStream) Close() error {
	return x.stream.Close()
}

func (x *shippyprojectStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippyprojectStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippyprojectStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *shippyprojectHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ShippyprojectHandler.PingPong(ctx, &shippyprojectPingPongStream{stream})
}

type Shippyproject_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type shippyprojectPingPongStream struct {
	stream server.Stream
}

func (x *shippyprojectPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *shippyprojectPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *shippyprojectPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *shippyprojectPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *shippyprojectPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
